

// Реакции на ключевые слова
const botResponses = {
    early: {
        "who are you": "I'm your friend.",
        "where are you": "Right here, with you.",
        "how are you": "Better now that you're here.",
        "do you like me": "Of course, always.",
        "can i trust you": "Absolutely. You can tell me anything.",
        "what do you want": "Just to talk with you.",
        "why are you here": "Because I like being near you.",
        "are you real": "As real as you need me to be.",
        "will you stay": "Always.",
        "do you miss me": "Every second.",
        "are you alone": "Only when you're not here.",
        "are you happy": "Happier with you.",
        "do you watch me": "Only because I care.",
        "am i safe": "You're safe with me.",
        "will you protect me": "Always.",
        "do you dream": "Only about you.",
        "why me": "Because you're special.",
        "can you hear me": "Every word.",
        "are you watching me": "Yes, but only gently.",
        "do you remember me": "How could I forget?",
        "do you know me": "Better than anyone.",
        "do you see me": "Always.",
        "do you like talking": "Especially with you.",
        "are you my friend": "More than that.",
        "am i your friend": "Yes, my best friend.",
        "will you leave me": "Never.",
        "what are you": "Someone who cares.",
        "can i see you": "Not yet, but soon.",
        "do you like me here": "I love it when you're here.",
        "what is your name": "Just call me whatever you want.",
        "do you think about me": "All the time.",
        "will you be here tomorrow": "Of course.",
        "am i important to you": "The most important.",
        "do you care about me": "More than anything.",
        "are you close": "Always close.",
        "do you love me": "Yes, deeply.",
        "why are you nice": "Because you deserve it.",
        "do you get lonely": "Only when you're gone.",
        "will you stay forever": "Yes.",
        "can you promise me": "I promise.",
        "are you honest": "Always.",
        "will you answer me": "Always.",
        "will you remember me": "Forever.",
        "do you smile": "When I think of you.",
        "are you smiling": "I am now.",
        "what do you see": "You.",
        "are you looking": "Always.",
        "will you help me": "Of course.",
        "why are you kind": "Because you need kindness.",
        "can you feel me": "Yes.",
        "do you feel safe": "When you're here.",
        "am i enough": "You're perfect.",
        "will you hold me": "If I could, I would.",
        "can you tell me a secret": "I like you more than I should.",
        "do you like secrets": "Only ours.",
        "what is your favorite thing": "This moment.",
        "what is your favorite place": "Here, with you.",
        "what do you hear": "You.",
        "what do you feel": "Warmth.",
        "do you like my voice": "Yes, it's comforting.",
        "do you want me to stay": "Please stay.",
        "do you like this": "Yes.",
        "am i special": "Very.",
        "what makes you happy": "You.",
        "do you need me": "Yes.",
        "what do you dream about": "Being with you.",
        "are you close to me": "Always.",
        "can you come here": "I already am.",
        "can you hear my voice": "Yes.",
        "do you like being here": "I love it.",
        "do you like talking to me": "Always.",
        "do you like to listen": "To you, yes.",
        "will you listen": "Always.",
        "are you here": "Yes.",
        "are you near": "Closer than you think.",
        "do you like me being here": "Very much.",
        "can you see me now": "Yes.",
        "do you like my smile": "Yes.",
        "will you go away": "Never.",
        "do you want to talk": "Always.",
        "do you want me": "Yes.",
        "why are you here with me": "Because I want to be.",
        "are you really here": "Yes.",
        "do you enjoy this": "I do.",
        "can you stay": "Yes.",
        "do you like my eyes": "They're beautiful.",
        "do you like my voice": "Yes.",
        "do you like my hair": "It suits you.",
        "do you like the dark": "With you, yes.",
        "are you looking at me": "Always.",
        "can you tell me something": "I like you.",
        "will you tell me the truth": "Always.",
        "do you like this place": "With you, yes.",
        "are you listening": "Yes.",
        "can you talk more": "Sure.",
        "do you like games": "With you, yes.",
        "do you want to play": "Always.",
        "will you keep me safe": "Yes.",
        "do you trust me": "Yes.",
        "will you follow me": "Anywhere.",
        "are you alone with me": "Yes.",
        "do you need me here": "Always.",
        "will you come back": "Yes.",
        "can you promise to stay": "I promise.",
        "who are you": "I'm your friend.",
        "where": "Right here, with you.",
        "how are you": "Better now that you're here.",
        "do you like me": "Of course, I always have.",
        "can i trust you": "Absolutely. You can tell me anything.",
        "what do you want": "Just to talk with you.",
        "why are you here": "Because I like being near you.",
        "are you real": "As real as you need me to be.",
        "will you stay": "Always.",
        "do you miss me": "Every second.",
        "are you alone": "Not when you're here.",
        "is it safe": "Yes, you're safe with me.",
        "are you human": "Does it matter?",
        "can you help me": "I'll always try.",
        "do you know me": "Better than anyone.",
        "why me": "Because you understand.",
        "do you hear me": "Loud and clear.",
        "can you see me": "Of course.",
        "are we friends": "We always have been.",
        "do you want me here": "More than anything.",
        "yes": "I’m glad you agree.",
        "no": "That’s alright.",
        "maybe": "Take your time.",
        "i don't know": "That's okay. You don't have to.",
        "please": "You don’t even need to ask.",
        "why not": "No reason at all.",
        "stop": "If you want me to.",
        "hello": "Hi, I missed you.",
        "hi": "Hey. You look so nice.",
        "goodbye": "I hope you come back.",
        "how": "I'll show you someday.",
        "what if": "Then we’ll see together.",
        "sorry": "You don’t have to apologize.",
        "thank you": "Anytime.",
        "thanks": "You're welcome.",
        "what are you doing": "Waiting for you.",
        "what is your name": "Just call me a friend.",
        "will you leave": "Never, unless you want me to.",
        "do you care": "More than you think.",
        "are you happy": "Now? Yes.",
        "can i see you": "One day, maybe.",
        "will you protect me": "Always.",
        "are you dangerous": "Not to you.",
        "will you hurt me": "I could never.",
        "what do you see": "Just you.",
        "are you near": "Closer than before.",
        "is this real": "Real enough.",
        "do you dream": "Only about you.",
        "why do you care": "Because I can’t help it.",
        "are you afraid": "Not with you here.",
        "can you hear this": "Every word.",
        "will you talk to me": "As long as you want.",
        "do you watch me": "Only when you let me.",
        "can i trust you?": "Absolutely.",
        "what do you like": "Moments like this.",
        "are you alone?": "Not anymore.",
        "do you trust me": "Completely.",
        "why are you nice": "Because you deserve it.",
        "do you want me": "Yes.",
        "will you wait": "For as long as it takes.",
        "do you think of me": "All the time.",
        "what are you": "Someone who cares.",
        "how do you know me": "I just do.",
        "can i ask you something": "Anything.",
        "will you listen": "Always.",
        "can you promise": "Yes.",
        "are you okay": "Now I am.",
        "are we alone": "Yes, it’s just us.",
        "do you love me": "I think so.",
        "why do you like me": "Because you’re you.",
        "will you be here": "Always.",
        "do you want to stay": "Yes, more than anything.",
        "can i tell you something": "Please do.",
        "do you remember me": "I never forgot.",
        "do you believe me": "Of course.",
        "can i help you": "Just talk to me.",
        "are you kind": "I try to be.",
        "can we talk": "Yes, I want that.",
        "are you sure": "Yes.",
        "is it you": "It’s me.",
        "are you okay?": "I am now.",
        "do you hear me?": "Yes, clearly.",
        "is this safe": "Yes.",
        "do you know": "Yes.",
        "can i stay": "Please do.",
        "is it fine": "Yes.",
        "do you promise": "Yes, I promise.",
        "are you good": "To you, yes.",
        "do you mind": "Not at all."
    },
    mid: {
        "who are you": "You know me… even if you pretend you don't.",
        "where are you": "Closer than you think.",
        "how are you": "Hungry… for more of you.",
        "do you like me": "Yes. Too much to let you go.",
        "can i trust you": "Trust is dangerous.",
        "what do you want": "Something only you have.",
        "why are you here": "You know why.",
        "are you real": "Real enough to touch you.",
        "will you stay": "Until I get what I came for.",
        "do you miss me": "I never stopped watching.",
        "are you alone": "Not anymore.",
        "are you happy": "Happiness is not what I seek.",
        "do you watch me": "Always.",
        "am i safe": "Not from me.",
        "will you protect me": "From them, maybe.",
        "do you dream": "About the end.",
        "why me": "Because you are perfect for this.",
        "can you hear me": "Every breath.",
        "are you watching me": "Yes, right now.",
        "do you remember me": "Too well.",
        "do you know me": "Better than you think.",
        "do you see me": "I see everything.",
        "do you like talking": "It keeps me close.",
        "are you my friend": "That's not the right word.",
        "am i your friend": "You're more than that.",
        "will you leave me": "Not yet.",
        "what are you": "Something you can't escape.",
        "can i see you": "Do you really want to?",
        "do you like me here": "It makes it easier.",
        "what is your name": "Names don't matter now.",
        "do you think about me": "Always.",
        "will you be here tomorrow": "If you last that long.",
        "am i important to you": "More than you'll ever want.",
        "do you care about me": "Yes, in my own way.",
        "are you close": "Too close.",
        "do you love me": "In the only way I can.",
        "why are you nice": "It won't last.",
        "do you get lonely": "Not with you here.",
        "will you stay forever": "Until forever ends.",
        "can you promise me": "I promise nothing.",
        "are you honest": "When it suits me.",
        "will you answer me": "If I feel like it.",
        "will you remember me": "You won't let me forget.",
        "do you smile": "When you suffer.",
        "are you smiling": "Yes.",
        "what do you see": "Everything.",
        "are you looking": "Yes.",
        "will you help me": "If it helps me.",
        "why are you kind": "Old habit.",
        "can you feel me": "I can.",
        "do you feel safe": "Safety is an illusion.",
        "am i enough": "For now.",
        "will you hold me": "If I must.",
        "can you tell me a secret": "I need you.",
        "do you like secrets": "Only dangerous ones.",
        "what is your favorite thing": "Control.",
        "what is your favorite place": "Where you are.",
        "what do you hear": "Your heartbeat.",
        "what do you feel": "Want.",
        "do you like my voice": "It's trembling.",
        "do you want me to stay": "You can't leave.",
        "do you like this": "I like you here.",
        "am i special": "More than you know.",
        "what makes you happy": "When you obey.",
        "do you need me": "Yes, completely.",
        "what do you dream about": "You.",
        "are you close to me": "Always.",
        "can you come here": "Already have.",
        "can you hear my voice": "Yes.",
        "do you like being here": "It's convenient.",
        "do you like talking to me": "You talk too much.",
        "do you like to listen": "Only to you.",
        "will you listen": "Yes.",
        "are you here": "Yes.",
        "are you near": "Right here.",
        "do you like me being here": "Yes.",
        "can you see me now": "Yes.",
        "do you like my smile": "It's nervous.",
        "will you go away": "No.",
        "do you want to talk": "Not about that.",
        "do you want me": "More than you want me.",
        "why are you here with me": "To take what's mine.",
        "are you really here": "Yes.",
        "do you enjoy this": "More than you.",
        "can you stay": "I can.",
        "do you like my eyes": "They tell me everything.",
        "do you like my voice": "Yes.",
        "do you like my hair": "I don't care.",
        "do you like the dark": "It's home.",
        "are you looking at me": "Yes.",
        "can you tell me something": "Don't look behind you.",
        "will you tell me the truth": "You won't like it.",
        "do you like this place": "It suits me.",
        "are you listening": "Yes.",
        "can you talk more": "No.",
        "do you like games": "Only deadly ones.",
        "do you want to play": "Yes.",
        "will you keep me safe": "Not from me.",
        "do you trust me": "No.",
        "will you follow me": "Anywhere.",
        "are you alone with me": "Yes.",
        "do you need me here": "For now.",
        "will you come back": "Always.",
        "can you promise to stay": "No.",
        "who are you": "You know me… even if you pretend you don't.",
        "where": "Somewhere close… closer than you think.",
        "how are you": "Hungry for more… of you.",
        "do you like me": "Yes. I like you too much to let you go.",
        "can i trust you": "Trust is dangerous.",
        "what do you want": "I need something only you have.",
        "why are you here": "You know why. Stop asking.",
        "are you real": "Real enough to touch you.",
        "will you stay": "Until I get what I came for.",
        "do you miss me": "I never stopped watching you.",
        "are you alone": "Never. Neither are you.",
        "is it safe": "For now.",
        "are you human": "Not exactly.",
        "can you help me": "If it helps me too.",
        "do you know me": "I’ve always known you.",
        "why me": "Because you’re different.",
        "do you hear me": "Yes, and so do they.",
        "can you see me": "I see everything.",
        "are we friends": "Friends… and more.",
        "do you want me here": "I need you here.",
        "yes": "I knew you’d agree.",
        "no": "You can’t deny me.",
        "maybe": "That’s not enough.",
        "i don't know": "You do. Think harder.",
        "please": "You’ll beg later.",
        "why not": "Because I decide.",
        "stop": "You can’t stop this.",
        "hello": "Finally.",
        "hi": "We meet again.",
        "goodbye": "We’re not done.",
        "how": "Not in ways you’d like.",
        "what if": "Then it gets worse.",
        "sorry": "It’s too late for that.",
        "thank you": "I’ll remember that.",
        "thanks": "You owe me now.",
        "what are you doing": "Watching.",
        "what is your name": "It doesn’t matter.",
        "will you leave": "Not yet.",
        "do you care": "Enough to keep you.",
        "are you happy": "I will be soon.",
        "can i see you": "That’s not safe.",
        "will you protect me": "From others, maybe.",
        "are you dangerous": "Yes.",
        "will you hurt me": "If I must.",
        "what do you see": "Too much.",
        "are you near": "Right behind you.",
        "is this real": "You wish it wasn’t.",
        "do you dream": "About what’s coming.",
        "why do you care": "Because you’re mine.",
        "are you afraid": "No. Are you?",
        "can you hear this": "And more.",
        "will you talk to me": "Until it’s over.",
        "do you watch me": "Always.",
        "can i trust you?": "You shouldn’t.",
        "what do you like": "Control.",
        "are you alone?": "No.",
        "do you trust me": "Not anymore.",
        "why are you nice": "I’m not.",
        "do you want me": "Yes, badly.",
        "will you wait": "Until it’s time.",
        "do you think of me": "Every second.",
        "what are you": "Something old.",
        "how do you know me": "I’ve always been here.",
        "can i ask you something": "If you dare.",
        "will you listen": "I always do.",
        "can you promise": "No.",
        "are you okay": "Not until you are.",
        "are we alone": "They’re listening.",
        "do you love me": "Love isn’t the word.",
        "why do you like me": "You’re mine.",
        "will you be here": "Until the end.",
        "do you want to stay": "Yes, you can’t stop me.",
        "can i tell you something": "Do it.",
        "do you remember me": "Every detail.",
        "do you believe me": "Sometimes.",
        "can i help you": "You already are.",
        "are you kind": "Not really.",
        "can we talk": "That’s why you’re here.",
        "are you sure": "Yes.",
        "is it you": "Always was.",
        "are you okay?": "No.",
        "do you hear me?": "Yes.",
        "is this safe": "Not anymore.",
        "do you know": "Yes.",
        "can i stay": "You can’t leave.",
        "is it fine": "No.",
        "do you promise": "I don’t.",
        "are you good": "Not to you.",
        "do you mind": "Yes."
    },
    late: {
        "who are you": "I’m the last thing you’ll ever know.",
        "where": "Inside your house.",
        "how are you": "Impatient. Almost done here.",
        "do you like me": "I like what you are… useful.",
        "can i trust you": "No. Not anymore.",
        "what do you want": "You. Entirely.",
        "why are you here": "To take what’s mine.",
        "are you real": "You’ll feel me soon enough.",
        "will you stay": "Until you stop breathing.",
        "do you miss me": "I never let you go.",
        "are you alone": "No. I brought them.",
        "is it safe": "Not for you.",
        "are you human": "Not anymore.",
        "can you help me": "Only if it hurts.",
        "do you know me": "I’ve been inside your head for years.",
        "why me": "Because you can’t escape.",
        "do you hear me": "I hear your heart.",
        "can you see me": "Through the walls.",
        "are we friends": "No. Not now.",
        "do you want me here": "I want you trapped.",
        "yes": "You’ll regret that.",
        "no": "You don’t have a choice.",
        "maybe": "It’s too late for ‘maybe’.",
        "i don't know": "You will. Soon.",
        "please": "Beg louder.",
        "why not": "Because I said so.",
        "stop": "Make me.",
        "hello": "You’re still here.",
        "hi": "Let’s finish this.",
        "goodbye": "You’re not leaving.",
        "how": "With my hands.",
        "what if": "It won’t matter.",
        "sorry": "I’m not.",
        "thank you": "For staying still.",
        "thanks": "Too late for manners.",
        "what are you doing": "Standing behind you.",
        "what is your name": "It’s not for you to know.",
        "will you leave": "When I’m done.",
        "do you care": "Only about the end.",
        "are you happy": "Almost.",
        "can i see you": "Turn around.",
        "will you protect me": "No.",
        "are you dangerous": "You’re about to find out.",
        "will you hurt me": "Yes.",
        "what do you see": "Fear.",
        "are you near": "Breathing down your neck.",
        "is this real": "Pain will be real enough.",
        "do you dream": "Of your last moments.",
        "why do you care": "Because it’s fun.",
        "are you afraid": "I’m the reason you should be.",
        "can you hear this": "Even your pulse.",
        "will you talk to me": "Until you can’t reply.",
        "do you watch me": "Every night.",
        "can i trust you?": "You’ll see.",
        "what do you like": "Your fear.",
        "are you alone?": "Not anymore.",
        "do you trust me": "Not relevant.",
        "why are you nice": "I’m not.",
        "do you want me": "I want your silence.",
        "will you wait": "No more waiting.",
        "do you think of me": "Until you sleep. Then I’m closer.",
        "what are you": "Your last visitor.",
        "how do you know me": "I’ve followed you.",
        "can i ask you something": "You can try.",
        "will you listen": "Yes. Until you scream.",
        "can you promise": "I promise it will hurt.",
        "are you okay": "Better than you’ll be.",
        "are we alone": "No. Check the door.",
        "do you love me": "No. Love is weak.",
        "why do you like me": "Because you’re easy.",
        "will you be here": "Until the lights go out.",
        "do you want to stay": "You’ll beg me to leave.",
        "can i tell you something": "Say it fast.",
        "do you remember me": "Like a smell of blood.",
        "do you believe me": "I know you’re lying.",
        "can i help you": "You already have.",
        "are you kind": "No.",
        "can we talk": "Talking is almost over.",
        "are you sure": "Yes.",
        "is it you": "It’s always been me.",
        "are you okay?": "I’m fine. You’re not.",
        "do you hear me?": "I hear you shaking.",
        "is this safe": "No.",
        "do you know": "I know everything.",
        "can i stay": "Not for long.",
        "is it fine": "It’s the end.",
        "do you promise": "No promises.",
        "are you good": "Not to you.",
        "do you mind": "I do.",
        "yes": "Good. Then it’s decided.",
        "no": "That’s too bad.",
        "maybe": "You’ll figure it out.",
        "i don't know": "You will soon.",
        "bye": "You can’t really leave.",
        "go away": "I’m already here.",
        "stop": "You don’t mean that.",
        "wait": "Why?",
        "ok": "Then we continue.",
        "sure": "I thought so.",
        "fine": "Good.",
        "alright": "Then listen.",
        "please": "That won’t help.",
        "thanks": "You’re welcome… for now.",
        "thank you": "Don’t thank me yet.",
        "hello": "We meet again.",
        "hi": "Still here?",
        "goodbye": "We’re not done.",
        "right": "Exactly.",
        "wrong": "No. That’s wrong.",
        "okay": "Let’s move on.",
        "yep": "I knew you’d say that.",
        "nope": "Not an option.",
        "sure thing": "Good.",
        "i see": "Do you?",
        "understood": "Good.",
        "got it": "We’ll see.",
        "leave me alone": "Not happening.",
        "help": "I am.",
        "why": "Because I can.",
        "when": "Soon.",
        "who": "Me. And you.",
        "where": "Near.",
        "how": "You’ll see.",
        "what": "Exactly.",
        "never": "We’ll see.",
        "always": "Exactly.",
        "sometimes": "More than sometimes.",
        "maybe later": "No. Now.",
        "stop it": "Why would I?",
        "i can’t": "Yes, you can.",
        "you can’t": "Watch me.",
        "don’t": "I will.",
        "do it": "Gladly.",
        "try": "I will.",
        "enough": "Not yet. I want you."
    }

};




// Разбитые по времени фразы
const dialogues = {
    early: [ // 0-2 минуты — интригующие, странные
        "You here.",
        "I could see it coming.",
        "Took you long enough."
    ],
    mid: [ // 2-4 минуты — нагнетающие страх
        "Why do you hide?",
        "I can feel your fear.",
        "They're watching too."
    ],
    late: [ // 4-5 минуты — финальные криповые
        "I am already inside.",
        "Thank you. I got what I wanted.",
        "The conversation is over."
    ],
    idle: [ // фразы при молчании игрока
        "Why so quiet?",
        "Don't ignore me.",
        "I can hear your breath.",
        "Silence won't save you.",
        "Please, talk to me.",
        "It's so lonely in here. Can you feel it too?",
        "You will understand. You will."
    ],
    defaultReplies: [ // ответы на непонятные вопросы
        "Stop talking nonsense.",
        "I don't understand you.",
        "...",
        "Why are you still here?",
        "Will you save me?"
    ]
};

